### ISSUE TITLE
release-prepare-mvn-pkg/prepare-release.sh leser inn snapshot-versjon med innrykk

### ISSUE THREAD

**Issue by s148719** [navikt/bidrag-actions#54]
release-prepare-mvn-pkg/prepare-release.sh leser inn snapshot-versjon med innrykk.

Endre

RELEASE_VERSION=$(cat pom.xml | grep version | grep SNAPSHOT | \  sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g')

til

RELEASE_VERSION=$(cat pom.xml | grep version | grep SNAPSHOT | \  sed 's/version//g' | sed 's/  //' | sed 's/-SNAPSHOT//' | sed 's;[</>];;g' | xargs)

for å bli kvitt problemet

**Comment by jactor-rises** [comment]
fixed when action was uptdated February 13th....
